# Generated by Django 4.0.4 on 2022-05-19 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('shortbio', models.CharField(default='null', max_length=90, null=True)),
                ('image', models.ImageField(default='images/home-profile.jpg', null=True, upload_to='images/')),
                ('phone', models.IntegerField(null=True)),
                ('role', models.CharField(default='user', max_length=15)),
                ('email', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
