# Generated by Django 4.0.4 on 2022-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bio_instagram_bio_twitter_alter_bio_role_job_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='images/home-profile.jpg', null=True, upload_to='images/'),
        ),
    ]
