# Generated by Django 4.0.4 on 2022-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='accepted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='rejected',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
