# Generated by Django 4.0.4 on 2022-06-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bio_accepted_bio_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='instagram_following',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='tiktok',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='tiktok_following',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='twitter_following',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
