# Generated by Django 4.0.4 on 2022-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bio_instagram_following_bio_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='youtube',
            field=models.CharField(default='null', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='youtube_following',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='instagram',
            field=models.CharField(default='null', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='tiktok',
            field=models.CharField(default='null', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='twitter',
            field=models.CharField(default='null', max_length=90, null=True),
        ),
    ]
